'use client';
import {useState,useEffect,useRef} from 'react';
export default function Dashboard(){
const[tab,sT]=useState('dashboard');
const[cb,sCb]=useState({});
const[st,sSt]=useState({});
const[pl,sPl]=useState([]);
const[rk,sRk]=useState([]);
const[lg,sLg]=useState([]);
const[cy,sCy]=useState(0);
const lr=useRef(null);
useEffect(()=>{la();triggerCron();const i1=setInterval(la,3000);const i2=setInterval(triggerCron,60000);return()=>{clearInterval(i1);clearInterval(i2)}},[]);
async function triggerCron(){try{const r=await fetch('/api/cron/auto');const d=await r.json();sCy(c=>c+1);sLg(p=>[{t:new Date().toLocaleTimeString('pt-BR'),m:'CRON | '+(d.acoes?.map(a=>a.nome+':'+a.status).join(', ')||'erro')+' | '+d.duracao_ms+'ms'},...p].slice(0,100))}catch(e){sLg(p=>[{t:new Date().toLocaleTimeString('pt-BR'),m:'CRON erro: '+e.message},...p].slice(0,100))}}
async function la(){const r=await Promise.allSettled([fetch('/api/cerebro/status').then(x=>x.json()),fetch('/api/state').then(x=>x.json()),fetch('/api/ranking').then(x=>x.json())]);if(r[0].status==='fulfilled')sCb(r[0].value);if(r[1].status==='fulfilled'){sSt(r[1].value);sPl((r[1].value.plano||[]).filter((p,i,a)=>a.findIndex(x=>x.dia===p.dia)===i).sort((a,b)=>a.dia-b.dia))}if(r[2].status==='fulfilled')sRk(r[2].value.ranking||[])}
const tabs=[{id:'dashboard',l:'\u229EDashboard'},{id:'cerebro',l:'\u{1F9E0}C\u00e9rebro AO VIVO'},{id:'gerador',l:'\u2728Gerador'},{id:'motor',l:'\u{1F501}Motor 1000x'},{id:'series',l:'\u{1F3AC}S\u00e9ries'},{id:'revelacao',l:'\u{1F389}Revela\u00e7\u00e3o 2027'},{id:'canais',l:'\u{1F4E1}Canais'},{id:'whatsapp',l:'\u{1F4AC}WhatsApp'},{id:'ranking',l:'\u{1F30D}Ranking'},{id:'cases',l:'\u{1F4C8}Cases'},{id:'playlist',l:'\u{1F4CB}Playlist 630d'},{id:'conteudo',l:'\u{1F4C4}Conte\u00fado'},{id:'monetizacao',l:'\u{1F4B0}Monetiza\u00e7\u00e3o'},{id:'config',l:'\u2699\uFE0FConfig'},{id:'logs',l:'\u{1F4CB}Logs'}];
const pur='#7c3aed',lp='#a78bfa',gn='#10b981';
const C=({children,s:sx})=><div style={{background:'rgba(0,0,0,0.4)',borderRadius:'1rem',padding:'1.5rem',border:'1px solid rgba(124,58,237,0.3)',marginBottom:'1rem',...(sx||{})}}>{children}</div>;
const M=({l,v,s:sub,t:tag})=><div style={{background:'rgba(124,58,237,0.1)',borderRadius:'0.75rem',padding:'1.25rem',border:'1px solid rgba(124,58,237,0.3)'}}><div style={{fontSize:'0.75rem',color:lp,marginBottom:'0.5rem',textTransform:'uppercase',letterSpacing:'0.1em',fontWeight:600}}>{l}{tag&&<span style={{display:'inline-block',padding:'0.2rem 0.6rem',background:'rgba(16,185,129,0.2)',color:gn,borderRadius:'0.3rem',fontSize:'0.7rem',fontWeight:700,marginLeft:'0.5rem'}}>{tag}</span>}</div><div style={{fontSize:'2.25rem',fontWeight:800,color:'#fff',lineHeight:1}}>{v}</div>{sub&&<div style={{fontSize:'0.8rem',color:lp,marginTop:'0.5rem'}}>{sub}</div>}</div>;
const G=({children})=><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:'1rem'}}>{children}</div>;
return(<div style={{minHeight:'100vh',background:'linear-gradient(135deg,#0a0118,#1a0b2e 50%,#2d1b4e)',color:'#e0d4f7',fontFamily:'system-ui'}}>
<style>{'@keyframes pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.6;transform:scale(1.2)}}'}</style>
<div style={{background:'rgba(0,0,0,0.5)',borderBottom:'2px solid rgba(124,58,237,0.5)',padding:'1rem',position:'sticky',top:0,zIndex:10}}><div style={{maxWidth:'1400px',margin:'0 auto',display:'flex',justifyContent:'space-between',alignItems:'center'}}><h1 style={{margin:0,fontSize:'1.5rem',fontWeight:800,background:'linear-gradient(90deg,'+lp+','+pur+')',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}><span style={{display:'inline-block',width:'0.6rem',height:'0.6rem',background:gn,borderRadius:'50%',marginRight:'0.5rem',animation:'pulse 1.5s infinite'}}/>psicologia.doc v7</h1><div style={{display:'flex',gap:'1rem',alignItems:'center',fontSize:'0.85rem'}}><span style={{color:gn}}>Ciclos: {cy}</span><span style={{color:lp}}>Dia {st.dia_atual||'\u2014'}</span></div></div></div>
<div style={{background:'rgba(0,0,0,0.3)',borderBottom:'1px solid rgba(124,58,237,0.3)',overflowX:'auto'}}><div style={{maxWidth:'1400px',margin:'0 auto',display:'flex',gap:'0.25rem',padding:'0.5rem 1rem'}}>{tabs.map(t=><button key={t.id} onClick={()=>sT(t.id)} style={{background:tab===t.id?'linear-gradient(135deg,'+pur+',#6d28d9)':'transparent',border:'none',borderRadius:'0.5rem',padding:'0.65rem 1.25rem',color:tab===t.id?'#fff':lp,cursor:'pointer',fontSize:'0.85rem',fontWeight:tab===t.id?600:500,whiteSpace:'nowrap'}}>{t.l}</button>)}</div></div>
<div style={{maxWidth:'1400px',margin:'1.5rem auto',padding:'0 1rem'}}>
{tab==='dashboard'&&<div><div style={{marginBottom:'1.5rem',padding:'1rem 1.5rem',background:'rgba(16,185,129,0.1)',borderLeft:'4px solid '+gn,borderRadius:'0.5rem'}}><strong style={{color:gn}}>Sistema 100% Aut\u00f4nomo \u2014 {cy} ciclos</strong><p style={{margin:'0.5rem 0 0',color:lp,fontSize:'0.9rem'}}>C\u00e9rebro roda a cada 60s via cron-job.org. Zero interven\u00e7\u00e3o. Mem\u00f3ria infinita.</p></div><G><M l="Dia" v={st.dia_atual||'\u2014'} s="Revela\u00e7\u00e3o: 261" t="AUTO"/><M l="Score" v={cb.score_medio_recente||cb.score||'\u2014'} s={cb.ultimo_topic?.slice(0,30)||''} t="LIVE"/><M l="Ciclos" v={cy} s="60s cron externo" t="CRON"/><M l="WA" v={st.membros_wa||0} s="Max: 1024" t="AUTO"/></G></div>}
{tab==='cerebro'&&<C><h2 style={{marginTop:0}}>\u{1F9E0} C\u00e9rebro AO VIVO</h2><p style={{color:lp}}>Autoaprendizado cont\u00ednuo. Cada ciclo salva em cerebro_memoria. Evolu\u00e7\u00e3o infinita.</p><G><M l="Status" v={(cb.status||'online').toUpperCase()}/><M l="\u00daltimo Ciclo" v={cb.ultimo_ciclo?new Date(cb.ultimo_ciclo).toLocaleTimeString('pt-BR'):'\u2014'}/><M l="Score M\u00e9dio" v={cb.score_medio_recente||'\u2014'}/><M l="Mem\u00f3ria" v={cb.total_memoria||0}/></G></C>}
{tab==='gerador'&&<C><h2 style={{marginTop:0}}>\u2728 Gerador Autom\u00e1tico</h2><p style={{color:lp}}>Roteiros 22-28min gerados pelo c\u00e9rebro automaticamente. /api/video/script roda a cada ciclo sem interven\u00e7\u00e3o.</p></C>}
{tab==='motor'&&<C><h2 style={{marginTop:0}}>\u{1F501} Motor 1000x \u2014 {cy} ciclos</h2><p style={{color:lp}}>cron-job.org (1x/min externo) + Vercel Cron (1x/dia backup). C\u00e9rebro auto-ajusta.</p><G>{['C\u00e9rebro','Aprendizado','WhatsApp','Ranking'].map(n=><M key={n} l={n} v="\u25CF ATIVO" s="60s cron externo"/>)}</G></C>}
{tab==='series'&&<C><h2 style={{marginTop:0}}>\u{1F3AC} S\u00e9ries Epis\u00f3dicas</h2><p style={{color:lp}}>C\u00e9rebro cria s\u00e9ries tem\u00e1ticas com epis\u00f3dios conectados automaticamente.</p></C>}
{tab==='revelacao'&&<C><h2 style={{marginTop:0}}>\u{1F389} Revela\u00e7\u00e3o Daniela Coelho \u2014 Dia 261</h2><div style={{paddingLeft:'2rem',marginTop:'1.5rem'}}>{pl.slice(0,10).map(p=>{const isR=p.dia===261;return <div key={p.dia} style={{position:'relative',paddingBottom:'1.25rem',borderLeft:isR?'3px solid '+pur:'3px solid rgba(124,58,237,0.3)',paddingLeft:'1.5rem'}}><div style={{position:'absolute',left:'-0.65rem',top:'0.1rem',width:'1.2rem',height:'1.2rem',borderRadius:'50%',background:isR?pur:'rgba(124,58,237,0.5)',border:'3px solid #1a0b2e'}}/><div style={{fontWeight:700,color:isR?pur:'#fff'}}>Dia {p.dia} [{p.fase}]</div><div style={{color:lp,fontSize:'0.9rem',marginTop:'0.25rem'}}>{p.acao}</div></div>})}</div></C>}
{tab==='canais'&&<C><h2 style={{marginTop:0}}>\u{1F4E1} Multi-Canais</h2><G>{[['YouTube','@psicologiadoc',gn],['Instagram','Pendente',lp],['TikTok','Pendente',lp],['Pinterest','Pendente',lp]].map(([n,v,c])=><M key={n} l={n} v={v}/>)}</G></C>}
{tab==='whatsapp'&&<C><h2 style={{marginTop:0}}>\u{1F4AC} WhatsApp Aut\u00f4nomo</h2><p style={{color:lp}}>Agente humanizado 8h-22h SP. Delay 2-45min. 100% autom\u00e1tico via cron.</p><G><M l="Status" v="\u25CF ATIVO" t="AUTO"/><M l="Membros" v={(st.membros_wa||0)+'/1024'}/><M l="Hor\u00e1rio" v="8h-22h SP"/></G></C>}
{tab==='ranking'&&<C><h2 style={{marginTop:0}}>\u{1F30D} Ranking Mundial</h2>{rk.length===0?<p style={{color:lp}}>C\u00e9rebro coletando dados do YouTube...</p>:rk.slice(0,10).map((r,i)=><div key={i} style={{padding:'0.85rem 1rem',background:i<3?'rgba(124,58,237,0.2)':'rgba(0,0,0,0.2)',borderRadius:'0.5rem',marginBottom:'0.5rem',display:'flex',justifyContent:'space-between',alignItems:'center',borderLeft:i<3?'4px solid '+pur:'4px solid transparent'}}><span><strong style={{color:pur}}>#{i+1}</strong> {r.topic}</span><span style={{color:'#fff',fontWeight:700,background:'rgba(124,58,237,0.3)',padding:'0.3rem 0.7rem',borderRadius:'0.3rem'}}>{r.score}/100</span></div>)}</C>}
{tab==='cases'&&<C><h2 style={{marginTop:0}}>\u{1F4C8} Cases do Dia</h2><G><M l="Melhor" v={rk[0]?.score||'\u2014'}/><M l="Total" v={rk.length}/><M l="M\u00e9dia" v={rk.length?Math.round(rk.reduce((a,b)=>a+(b.score||0),0)/rk.length):'\u2014'}/></G></C>}
{tab==='playlist'&&<C><h2 style={{marginTop:0}}>\u{1F4CB} Playlist 630 dias</h2><div style={{marginTop:'1rem'}}>{pl.map((p,i)=><div key={i} style={{padding:'0.6rem 0.75rem',borderBottom:'1px solid rgba(124,58,237,0.2)',display:'flex',justifyContent:'space-between'}}><span><strong>Dia {p.dia}</strong> \u2014 {p.acao}</span><span style={{color:lp,fontSize:'0.85rem'}}>{p.fase}</span></div>)}</div></C>}
{tab==='conteudo'&&<C><h2 style={{marginTop:0}}>\u{1F4C4} Biblioteca</h2><G><M l="Roteiros" v="\u2014"/><M l="V\u00eddeos" v="\u2014"/></G></C>}
{tab==='monetizacao'&&<C><h2 style={{marginTop:0}}>\u{1F4B0} Monetiza\u00e7\u00e3o</h2><G><M l="AdSense" v="Pendente" s="1K subs + 4K horas"/><M l="Afiliados" v="R$ 0"/><M l="Consultas" v="Dia 261+" s="P\u00f3s-revela\u00e7\u00e3o"/></G></C>}
{tab==='config'&&<C><h2 style={{marginTop:0}}>\u2699\uFE0F Config</h2><div style={{color:lp,lineHeight:1.8}}><p><strong>Stack:</strong> Next.js 14 + Supabase + Groq 14.400/dia</p><p><strong>Deploy:</strong> repovazio.vercel.app</p><p><strong>Crons:</strong> cron-job.org 1x/min + Vercel 1x/dia</p><p><strong>Evolu\u00e7\u00e3o:</strong> Infinita em cerebro_memoria</p></div></C>}
{tab==='logs'&&<C><h2 style={{marginTop:0}}>\u{1F4CB} Logs</h2><div ref={lr} style={{background:'rgba(0,0,0,0.5)',borderRadius:'0.5rem',padding:'1rem',maxHeight:'500px',overflowY:'auto',fontFamily:'ui-monospace,monospace',fontSize:'0.8rem'}}>{lg.length===0?<div style={{color:lp}}>Aguardando primeiro ciclo (60s)...</div>:lg.map((l,i)=><div key={i} style={{marginBottom:'0.3rem',color:gn}}><span style={{color:lp}}>[{l.t}]</span> {l.m}</div>)}</div></C>}
</div></div>)}